version: "3.8"

services:
  knn-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${APP_PORT:-1324}:1324"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: knn-meysner-app
